server:
  port: 8083

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/platform
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
